trigger:
  branches:
    include:
      - main
      - dev
      - qa

pr: none

pool: Default

variables:
  environment: ''

steps:
- script: |
    echo "Determining environment based on branch..."
    if [[ "$(Build.SourceBranch)" == "refs/heads/main" ]]; then
      echo "Setting environment to production"
      echo "##vso[task.setvariable variable=environment]prod"
    elif [[ "$(Build.SourceBranch)" == "refs/heads/dev" ]]; then
      echo "Setting environment to development"
      echo "##vso[task.setvariable variable=environment]dev"
    elif [[ "$(Build.SourceBranch)" == "refs/heads/qa" ]]; then
      echo "Setting environment to QA"
      echo "##vso[task.setvariable variable=environment]qa"
    else
      echo "No matching branch found, defaulting to development"
      echo "##vso[task.setvariable variable=environment]dev"
    fi  # Ensure the 'if' block is properly closed
  displayName: 'Set environment based on branch'

- script: |
    echo "Environment set to $(environment)"
    databricks bundle validate
    databricks bundle deploy -t $(environment)
  displayName: 'Validate and Deploy'
