trigger:
  branches:
    include:
      - main
      - dev
      - qa

pr: none

pool: Default

steps:
- script: echo "Hello, world!"
  displayName: 'Run a one-line script'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      echo 'Hello world'

      databricks bundle validate
      databricks bundle deploy -t dev