parameters:
- name: environment
  displayName: 'Choose Environment'
  type: string
  default: dev
  values:
    - dev
    - qa
    - prod

trigger:
  branches:
    include:
      - main
      - dev
      - qa

pr: none

pool: Default

steps:
- script: echo "Hello, world!"
  displayName: 'Run a one-line script'

- script: |
    echo Running for environment: ${{ parameters.environment }}
  displayName: 'Print Environment'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Deploying to environment: ${{ parameters.environment }}"

      databricks bundle validate
      databricks bundle deploy -t ${{ parameters.environment }}
  displayName: 'Deploy Databricks Bundle'
